package com.github.xandergos.terraindiffusionmc.world.surface;

import com.github.xandergos.terraindiffusionmc.biome.TerrainBiomeRegistry;
import com.github.xandergos.terraindiffusionmc.pipeline.LocalTerrainProvider.HeightmapData;
import com.github.xandergos.terraindiffusionmc.worldgen.surface.SiteGrid;
import com.github.xandergos.terraindiffusionmc.worldgen.surface.SurfaceNoise;
import com.github.xandergos.terraindiffusionmc.worldgen.surface.TerrainSampling;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.levelgen.Heightmap;

/**
 * Pressure ridges on frozen rivers and lakes. Uses the single-anchor pattern from
 * {@link BoulderFeaturePlacer} but stamps a linear ridge shape instead of a blob. The ridge
 * is oriented in a random direction and has a wavy top generated by value noise.
 */
public final class PressureRidgeFeaturePlacer implements SurfaceFeaturePlacer {
    private static final long SALT = 0x50524553L;
    private static final int CELL_SIZE = 40;
    private static final float SPAWN_CHANCE = 0.2f;

    @Override
    public String id() {
        return "pressure_ridge";
    }

    @Override
    public int cellSizeBlocks() {
        return CELL_SIZE;
    }

    @Override
    public int maxReachBlocks() {
        return 12;
    }

    @Override
    public long salt() {
        return SALT;
    }

    @Override
    public void place(ChunkAccess chunk, HeightmapData data, int dataOriginX, int dataOriginZ,
                       SiteGrid.Site site, long worldSeed) {
        int localX = site.worldX() - chunk.getPos().getMinBlockX();
        int localZ = site.worldZ() - chunk.getPos().getMinBlockZ();
        if (localX < 0 || localX > 15 || localZ < 0 || localZ > 15) return;

        if (SurfaceNoise.unitHash(worldSeed ^ SALT, site.worldX(), site.worldZ()) >= SPAWN_CHANCE) return;

        int row = site.worldZ() - dataOriginZ;
        int col = site.worldX() - dataOriginX;
        if (!TerrainSampling.inBounds(data, row, col)) return;

        float elevation = TerrainSampling.elevationAt(data, row, col);
        if (elevation < 0 || elevation > 5) return;

        TerrainBiomeRegistry registry = TerrainBiomeRegistry.instance();
        short biomeIndex = TerrainSampling.biomeIndexAt(data, row, col);
        String biomeKey = registry.keyForIndex(biomeIndex);
        if (biomeKey == null || !(biomeKey.contains("frozen") || biomeKey.contains("ice_spikes"))) {
            return;
        }

        boolean nearWater = hasFluvialWater(data, row, col);
        if (!nearWater && SurfaceNoise.unitHash(worldSeed ^ SALT, site.worldX(), site.worldZ() + 500) > 0.5f) return;

        int groundY = chunk.getHeight(Heightmap.Types.WORLD_SURFACE_WG, localX, localZ) - 1;
        if (groundY <= chunk.getMinY()) return;
        BlockPos.MutableBlockPos probe = new BlockPos.MutableBlockPos(site.worldX(), groundY, site.worldZ());
        if (chunk.getBlockState(probe).isAir()) return;

        stamp(chunk, site, groundY);
    }

    private void stamp(ChunkAccess chunk, SiteGrid.Site site, int groundY) {
        Heightmap worldSurface = chunk.getOrCreateHeightmapUnprimed(Heightmap.Types.WORLD_SURFACE_WG);
        Heightmap motionBlocking = chunk.getOrCreateHeightmapUnprimed(Heightmap.Types.MOTION_BLOCKING);
        BlockPos.MutableBlockPos pos = new BlockPos.MutableBlockPos();
        int minX = chunk.getPos().getMinBlockX();
        int minZ = chunk.getPos().getMinBlockZ();

        float angle = SurfaceNoise.unitHash(site.seed(), 0, 0) * (float) (Math.PI * 2);
        int dirX = Math.round((float) Math.cos(angle));
        int dirZ = Math.round((float) Math.sin(angle));
        if (dirX == 0 && dirZ == 0) dirX = 1;

        int ridgeLength = 6 + (int) (SurfaceNoise.unitHash(site.seed(), 1, 0) * 5);
        int ridgeWidth = 1 + (int) (SurfaceNoise.unitHash(site.seed(), 2, 0) * 2);
        int baseHeight = 1 + (int) (SurfaceNoise.unitHash(site.seed(), 3, 0) * 2);

        for (int li = 0; li < ridgeLength; li++) {
            int ridgeX = site.worldX() + dirX * li;
            int ridgeZ = site.worldZ() + dirZ * li;
            int lrx = ridgeX - minX;
            int lrz = ridgeZ - minZ;
            if (lrx < 0 || lrx > 15 || lrz < 0 || lrz > 15) continue;

            float noiseVal = SurfaceNoise.valueNoise(site.seed() ^ 0x52494447L,
                    (float) ridgeX / 8.0f, (float) ridgeZ / 8.0f);
            int height = baseHeight + (noiseVal > 0 ? 1 : 0);

            for (int w = -ridgeWidth / 2; w <= ridgeWidth / 2; w++) {
                int perpX = -dirZ * w;
                int perpZ = dirX * w;
                int wx = ridgeX + perpX;
                int wz = ridgeZ + perpZ;
                int lx = wx - minX;
                int lz = wz - minZ;
                if (lx < 0 || lx > 15 || lz < 0 || lz > 15) continue;

                for (int dy = 0; dy < height; dy++) {
                    int worldY = groundY + 1 + dy;
                    pos.set(wx, worldY, wz);
                    if (!chunk.getBlockState(pos).isAir()) continue;
                    BlockState block = iceFor(site.seed(), wx, worldY, wz);
                    chunk.setBlockState(pos, block);
                    worldSurface.update(lx, worldY, lz, block);
                    motionBlocking.update(lx, worldY, lz, block);
                }
            }
        }
    }

    private static BlockState iceFor(long seed, int x, int y, int z) {
        return SurfaceNoise.unitHash(seed ^ 0x50524944474CL, x, z) < 0.5f
                ? Blocks.PACKED_ICE.defaultBlockState()
                : Blocks.ICE.defaultBlockState();
    }

    private static boolean hasFluvialWater(HeightmapData data, int row, int col) {
        if (data.riverWaterSurface != null) {
            return data.riverWaterSurface[row][col] != HeightmapData.NO_FLUVIAL_WATER;
        }
        if (data.riverWater != null) {
            return data.riverWater[row][col] != 0;
        }
        return false;
    }
}
