#!/usr/bin/env python3
"""Reclaim the overworld from a mod that overrides `minecraft:dimension/overworld`.

THE PROBLEM
-----------
terrain-diffusion installs its terrain by registering a *world preset* and adding it to the
`normal` preset tag, so the player picks "Terrain Diffusion" as a world type. Total-conversion
mods instead ship `data/minecraft/dimension/overworld.json` in their jar, which redefines the
overworld dimension outright. `minecraft:dimension` is a datapack-loaded registry, and a
datapack entry beats the preset -- so the overworld silently reverts to their generator even
when the player picked our world type, and the resulting choice is baked into level.dat at
creation.

THE FIX
-------
Datapacks in a world's own `datapacks/` folder load *after* mod-provided ones, so an
`overworld.json` there outranks the mod's. This writes that datapack, lifting the overworld
entry straight out of terrain-diffusion's own world preset so the two can never drift apart.

Nothing here is specific to any one mod, and nothing from another mod is copied -- it only
restates our own dimension definition at a higher priority.

USAGE
-----
    python3 build_overworld_datapack.py \\
        --output "~/.../saves/My World/datapacks/terrain-diffusion-overworld.zip" [--scale 2]

Then **create a new world** with the datapack enabled (world creation -> Data Packs), or drop it
into an existing world's `datapacks/` folder. Adding it to a world whose chunks were already
generated by the other mod leaves a hard seam where the old chunks end -- a fresh world is
strongly preferred.

--scale mirrors the slider on the terrain-diffusion world-creation screen, which normally swaps
the overworld's dimension type to `terrain_diffusion_scale_<N>` (heights 464/800/1136/1472/1808/
2032 for 1-6). That screen's choice is lost when the dimension is overridden, so set it here
instead. Omitting it uses the preset's default, which matches scale 2.
"""
import argparse
import json
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DATA = REPO / "versions/1.21.1/common/src/main/resources/data/terrain-diffusion-mc"
WORLD_PRESET = DATA / "worldgen/world_preset/terrain_diffusion.json"

OUTPUT_ENTRY = "data/minecraft/dimension/overworld.json"

PACK_MCMETA = {
    "pack": {
        "description": "Terrain Diffusion overworld (overrides other worldgen mods)",
        "pack_format": 48,
        "supported_formats": {"min_inclusive": 48, "max_inclusive": 99},
    }
}


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output", required=True, type=Path,
                        help="Datapack zip to write, e.g. '<world>/datapacks/td-overworld.zip'")
    parser.add_argument("--scale", type=int, choices=range(1, 7), default=None,
                        help="Terrain scale 1-6, as on the world-creation screen. "
                             "Default: the preset's own dimension type (equivalent to 2).")
    parser.add_argument("--preset", type=Path, default=WORLD_PRESET,
                        help="World preset to lift the overworld entry from.")
    args = parser.parse_args()

    if not args.preset.exists():
        raise SystemExit(f"No such file: {args.preset}")

    preset = json.loads(args.preset.read_text())
    try:
        overworld = preset["dimensions"]["minecraft:overworld"]
    except KeyError:
        raise SystemExit(f"{args.preset} has no dimensions -> minecraft:overworld entry.")

    # A LevelStem and a world preset's dimension entry are the same shape ({type, generator}),
    # so the preset's entry can be written out verbatim apart from the scale swap.
    level_stem = json.loads(json.dumps(overworld))
    if args.scale is not None:
        level_stem["type"] = f"terrain-diffusion-mc:terrain_diffusion_scale_{args.scale}"

    output = args.output.expanduser()
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as out:
        out.writestr("pack.mcmeta", json.dumps(PACK_MCMETA, indent=2))
        out.writestr(OUTPUT_ENTRY, json.dumps(level_stem, indent=2))

    print(f"dimension type: {level_stem['type']}")
    print(f"generator:      {level_stem['generator'].get('settings')} / "
          f"{level_stem['generator'].get('biome_source', {}).get('type')}")
    print(f"wrote {output}")
    print("Create a NEW world with this datapack enabled (Data Packs button on the world screen).")


if __name__ == "__main__":
    main()
